# Generated by Django 5.1.7 on 2025-04-25 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("description", models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                (
                    "programmes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patientmgr.healthprogram",
                    ),
                ),
            ],
        ),
    ]
