# Generated by Django 5.1.7 on 2025-04-25 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientmgr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProgrammes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patientmgr.healthprogram",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="patient",
            name="programmes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patientmgr.patientprogrammes",
            ),
        ),
    ]
