# Generated by Django 5.1.7 on 2025-04-25 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientmgr", "0002_patientprogrammes_alter_patient_programmes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientprogrammes",
            old_name="program",
            new_name="programmes",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="programmes",
        ),
        migrations.AddField(
            model_name="patientprogrammes",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="patientmgr.patient",
            ),
            preserve_default=False,
        ),
    ]
