# Generated by Django 5.1.7 on 2025-04-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patientmgr", "0003_rename_program_patientprogrammes_programmes_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PatientProgrammes",
            new_name="PatientProgram",
        ),
        migrations.RenameField(
            model_name="patientprogram",
            old_name="programmes",
            new_name="program",
        ),
    ]
