# Generated by Django 5.1.7 on 2025-04-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientmgr", "0007_alter_patientprogram_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprogram",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programmes",
                to="patientmgr.patient",
            ),
        ),
        migrations.AlterField(
            model_name="patientprogram",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patientmgr.healthprogram",
            ),
        ),
    ]
